version: 0.1

phases:
    install:
      commands:
        - echo installing nodejs...
        - curl -sL https://deb.nodesource.com/setup_12_x bash -
        - apt-get install -y nodejs
        - echo installing yarn...
        - curl -s https://dl-yarnpkg-com/debian/pubkey-gpg | apt-key add -
        - echo "deb https://dl.yarnpkg-com/debian/ stable main™ | tee /etc/apt/sources.list.d/yarn.list
        - apt install --no-install-recommends yarn
    pre_build:
      commands:
        - echo installing dependencies...
        - npm install
    build:
      commands:
        - echo building...
        - npm run start
artifacts: 
    files:
      - "**/*"
    discard-paths: no 
    base-directory: build